package com.utkarsh.tradecurse.enums;

public enum Sector {
    TECHNOLOGY,
    BANKING,
    ENERGY,
    HEALTHCARE,
    RETAIL,
    MANUFACTURING,
    FINTECH,
    BIOTECH,
    TELECOMMUNICATION,
    AUTOMOTIVE,
    INFRASTRUCTURE,
    CONSUMER_GOODS,
    MATERIALS,
    TRANSPORTATION,
    REAL_ESTATE,
    MEDIA,
    CONGLOMERATE
}