spring.application.name=TradeCurse

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8081

spring.config.import=optional:file:.env[.properties]

app.frontend-url=${FRONTEND_URL}
app.jwt-secret-key=${JWT_SECRET_KEY}